//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGrage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public int MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChiNCC { get; set; }
        public string DienThoaiNCC { get; set; }
        public string MaSoThueNCC { get; set; }
        public string Email { get; set; }
        public string LoaiHinh { get; set; }
        public string HoTenNguoiDaiDien { get; set; }
    }
}
