//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTONKHO
    {
        public string MaBCTK { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string BCTK_MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
