//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOGIA()
        {
            this.CT_BAOGIA = new HashSet<CT_BAOGIA>();
        }
    
        public string MaBG { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string BG_MaKH { get; set; }
        public string BG_BienSoXe { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
        public string BG_MaTN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
        public virtual THONGTINTIEPNHAN THONGTINTIEPNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAOGIA> CT_BAOGIA { get; set; }
    }
}
