//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHANH
    {
        public string MaBH { get; set; }
        public string BH_MaKH { get; set; }
        public string BH_BienSoXe { get; set; }
        public string BH_MaHH { get; set; }
        public Nullable<int> ThoiHanBaoHanh { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string NoiBaoHanh { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
    }
}
