//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAOGIA
    {
        public string CTBG_MaHH { get; set; }
        public string CTBG_MaBG { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual BAOGIA BAOGIA { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
