//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_XUATKHO
    {
        public string CTXK_MaHH { get; set; }
        public string CTXK_MaXK { get; set; }
        public Nullable<int> SoLuongXuatKho { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual XUATKHO XUATKHO { get; set; }
    }
}
