//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIADICHVU
    {
        public string MaDGDV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string DGDV_MaTN { get; set; }
        public Nullable<int> MucDoDichVu { get; set; }
        public Nullable<int> MucDoThaiDo { get; set; }
        public Nullable<int> MucDoChatLuong { get; set; }
        public string GopYKhac { get; set; }
    
        public virtual THONGTINTIEPNHAN THONGTINTIEPNHAN { get; set; }
    }
}
