//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATLICH
    {
        public string MaDL { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string DL_MaKH { get; set; }
        public string DL_BienSoXe { get; set; }
        public string TinhTrangXe { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public string GhiChuKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
    }
}
