//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.BAOHANHs = new HashSet<BAOHANH>();
            this.CT_BAOGIA = new HashSet<CT_BAOGIA>();
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.CT_NHAPKHO = new HashSet<CT_NHAPKHO>();
            this.CT_XUATKHO = new HashSet<CT_XUATKHO>();
        }
    
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public decimal DonGia { get; set; }
        public string DonViTinh { get; set; }
        public string LoaiHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> SoLuongTmp { get; set; }
        public string HinhAnh { get; set; }
        public string HH_MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHANH> BAOHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAOGIA> CT_BAOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_NHAPKHO> CT_NHAPKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_XUATKHO> CT_XUATKHO { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
