//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTHU()
        {
            this.CT_TRAGOP = new HashSet<CT_TRAGOP>();
        }
    
        public string MaPT { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string DiaChi { get; set; }
        public string LyDoNop { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string ChungTuGoc { get; set; }
        public string PT_MaKH { get; set; }
        public string PT_MaNV { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TRAGOP> CT_TRAGOP { get; set; }
    }
}
