//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINTIEPNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINTIEPNHAN()
        {
            this.BANGIAOXEs = new HashSet<BANGIAOXE>();
            this.BAOGIAs = new HashSet<BAOGIA>();
            this.DANHGIADICHVUs = new HashSet<DANHGIADICHVU>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MaTN { get; set; }
        public string TN_MaKH { get; set; }
        public string TN_BienSoXe { get; set; }
        public string TN_MaNV { get; set; }
        public Nullable<System.DateTime> ThoiGianTiepNhan { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoDuKien { get; set; }
        public string GhiChuKH { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGIAOXE> BANGIAOXEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOGIA> BAOGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIADICHVU> DANHGIADICHVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
    }
}
