//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrieUnityGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAGOP
    {
        public string MaTG { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string TG_MaHD { get; set; }
        public string TG_MaKH { get; set; }
        public Nullable<decimal> SoTienTraGop { get; set; }
        public Nullable<System.DateTime> NgayTraDinhKi { get; set; }
        public Nullable<double> TyLeTraGop { get; set; }
        public Nullable<int> ThoiHanTra { get; set; }
        public Nullable<decimal> SoTienDaTra { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
